# Generated by Django 3.2.2 on 2021-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Project name')),
                ('project_type', models.CharField(choices=[('C', 'Classification'), ('R', 'Regression')], max_length=1)),
            ],
        ),
    ]
