# Generated by Django 3.2.2 on 2021-05-13 10:12

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to=ai.models.user_directory_path),
        ),
    ]
