# Generated by Django 3.2.2 on 2021-05-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_project_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model name')),
                ('accuracy', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_classification', to='ai.project')),
            ],
        ),
    ]
