# Generated by Django 3.2.2 on 2021-05-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_classificationreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationreport',
            name='model_path',
            field=models.FilePathField(default=''),
        ),
    ]
