# Generated by Django 3.2.2 on 2021-05-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_classificationreport_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationreport',
            name='model_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
