# Generated by Django 3.2.2 on 2021-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_classificationreport_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='label',
            field=models.CharField(default='label', max_length=20, verbose_name='label column name'),
        ),
    ]
